// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsgaehqrxqdtynxmlxmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzZ2FlaHFyeHFkdHlueG1seG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMTA2MjksImV4cCI6MjA4NjU4NjYyOX0.VTvnUw2mbh7sny-k72zSKq_Xa6rJB5E2s9byfYq56G0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});